# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    book_dir: '%kernel.project_dir%/var/book-uploads'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands,ø event subscribers, etc.
        bind:
            $bookDir: '%book_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Infrastructure\:
        resource: '../src/Infrastructure/*'
        exclude: '../src/Infrastructure/{Statistic,Query.php,File.php}'

    App\Application\:
        resource: '../src/Application/*'
        exclude: '../src/Application/Parser/{NormalizedBookAttributes.php,ParsedBookAttributes.php}'

    App\Application\Command\:
        resource: '../src/Application/Command'
        tags: ['controller.command']

    App\Application\Downloader: '@App\Infrastructure\FilesystemDownloader'
    App\Application\Uploader: '@App\Infrastructure\FilesystemUploader'

    App\Application\Parser\Parser:
        calls:
            - [addMimeTypeParser, ['@App\Infrastructure\Parser\EpubParser']]
            - [addMimeTypeParser, ['@App\Infrastructure\Parser\Fb2Parser']]

